org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.3
enabled_platforms=fabric,neoforge

archives_base_name=semi
mod_version=1.1.24
maven_group=dev.emi

fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3

forge_version=1.20.4-49.0.9

neoforge_version=26.3.0.8-beta

jei_version=jei-26.3-fabric:31.4.0.19
