modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config="emi.mixins.json"

[[mixins]]
config="emi-neoforge.mixins.json"

[[mods]]
modId = "emi"
version = "${version}"
displayName = "EMI"
authors = "Emi"
description = '''
A featureful and accessible item and recipe viewer
'''
logoFile = "icon.png"

[[dependencies.emi]]
modId="neoforge"
type="REQUIRED"
versionRange="[26.1,27)"
ordering="NONE"
side="BOTH"

[[dependencies.emi]]
modId="minecraft"
type="REQUIRED"
versionRange="[26.1,26.2)"
ordering="NONE"
side="BOTH"
