import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath 'com.modrinth.minotaur:Minotaur:2.4.3'
		classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
	}
}

plugins {
	id "dev.architectury.loom-no-remap"
	id "com.gradleup.shadow" version "9.4.1"
}
if (System.getenv("MODRINTH_TOKEN")) {
	apply plugin: "com.modrinth.minotaur"
}
if (System.getenv("CURSEFORGE_TOKEN")) {
	apply plugin: "com.matthewprenger.cursegradle"
}
evaluationDependsOn ':xplat'

architectury {
	platformSetupLoomIde()
	neoForge()
}

loom {
	accessWidenerPath = project(":xplat").loom.accessWidenerPath

	mods {
		main {
			sourceSet project(':xplat').sourceSets.main
		}
	}
}

repositories {
	maven {
		url "https://maven.neoforged.net/releases/"
		content {
			includeGroupAndSubgroups "net.neoforged"
			includeGroupAndSubgroups "cpw.mods"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url "https://cursemaven.com"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
}

configurations {
	common
	shadowCommon
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentNeoForge.extendsFrom common
}

dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

	neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

	common(project(path: ":xplat")) { transitive = false }
	shadowCommon(project(path: ":xplat", configuration: "transformProductionNeoForge")) { transitive = false }

	localRuntime "curse.maven:jei-238222:8419117"
	localRuntime "curse.maven:refined-storage-243076:8211383"
	localRuntime "curse.maven:applied-energistics-2-223794:8257570"
	localRuntime "curse.maven:guideme-1173950:8204880"
	localRuntime "curse.maven:cooking-for-blockheads-231484:8404511"
	localRuntime "curse.maven:balm-531761:8424855"
	localRuntime "curse.maven:energized-power-782147:8400272"
	localRuntime "curse.maven:just-dire-things-1002348:8251776"
	localRuntime "curse.maven:inventory-essentials-368825:8362291"
	localRuntime "curse.maven:jade-324717:8326300"
	localRuntime "curse.maven:logistics-network-1448257:8419032"
	localRuntime "curse.maven:pipez-443900:8351634"
	localRuntime "curse.maven:powah-rearchitected-633483:8025339"
	localRuntime "curse.maven:cloth-config-348521:7817583"
	localRuntime "curse.maven:refined-storage-jei-integration-1230497:8175469"
	localRuntime "curse.maven:sophisticated-backpacks-422301:8377448"
	localRuntime "curse.maven:sophisticated-core-618298:8412279"
	localRuntime "curse.maven:yeetusexperimentus-635427:7830957"
	localRuntime "curse.maven:productivebees-377897:8303935"
	localRuntime "curse.maven:cucumber-272335:8433624"
	localRuntime "curse.maven:mystical-agriculture-246640:8344253"
	localRuntime "curse.maven:mystical-automation-1265613:8205860"
	localRuntime "curse.maven:patchouli-306770:8404543"
	localRuntime "curse.maven:placebo-283644:8249025"
	localRuntime "curse.maven:apothic-attributes-898963:8182592"
	localRuntime "curse.maven:apothic-enchanting-1063926:8171092"
	localRuntime "curse.maven:apothic-spawners-986583:8171043"
	localRuntime "curse.maven:apotheosis-313970:8249091"
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "version": project.version
	}
}

def shadowJar = tasks.named('shadowJar', ShadowJar)

shadowJar.configure { ShadowJar jar ->
	jar.exclude "fabric.mod.json"
	jar.exclude "architectury.common.json"

	jar.configurations = [project.configurations.shadowCommon]
	jar.archiveClassifier = ""
}

tasks.named('jar', Jar).configure {
	archiveClassifier = "dev"
}

def sourcesJar = tasks.named('sourcesJar', Jar)

sourcesJar.configure { Jar jar ->
	def commonSources = project(":xplat").tasks.named("sourcesJar", Jar)
	dependsOn commonSources
	jar.from zipTree(commonSources.get().archiveFile)
	//TODO: Fix this in a better way that doesn't lead to stripping out the jemi sources
	jar.exclude 'dev/emi/emi/jemi/**'
}

def filteredSourcesJar = tasks.register('filteredSourcesJar', Jar, {
	archiveClassifier = 'filtered-sources'
	dependsOn sourcesJar
	from zipTree(sourcesJar.get().archiveFile)
	exclude 'dev/emi/emi/jemi/**'
})

def apiJar = tasks.register('apiJar', Jar, {
	archiveClassifier = 'api'
	dependsOn shadowJar
	from zipTree(shadowJar.get().archiveFile)
	include 'LICENSE'
	include 'emi.mixins.json'
	include 'emi-neoforge.mixins.json'
	include 'emi.accesswidener'
	include 'dev/emi/emi/api/**'
	exclude 'dev/emi/emi/api/EmiRecipeHandler**'
	exclude 'dev/emi/emi/api/stack/FluidEmiStack**'
	exclude 'dev/emi/emi/api/stack/ItemEmiStack**'
	exclude 'dev/emi/emi/api/stack/EmptyEmiStack**'
	exclude 'dev/emi/emi/api/stack/TagEmiIngredient**'
	exclude 'dev/emi/emi/api/stack/ListEmiIngredient**'
})

tasks.named("build").configure {
	dependsOn(filteredSourcesJar, apiJar)
}

components.java {
	withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
		skip()
	}
}

publishing {
	publications {
		register('maven', MavenPublication) {
			artifactId = "${rootProject.name}-${project.name}"
			version = project.ext.mavenVersion
			artifact(shadowJar) {
				builtBy shadowJar
				classifier ''
			}
			artifact(filteredSourcesJar) {
				builtBy filteredSourcesJar
				classifier 'sources'
			}
			artifact(apiJar) {
				builtBy apiJar
				classifier 'api'
			}
		}
	}
	setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
	if (project.hasProperty("mavenUrl")) {
		repositories.maven {
			url project.mavenUrl
			credentials {
				username project.mavenUsername
				password project.mavenPassword
			}
		}
	}
}

if (System.getenv("MODRINTH_TOKEN")) {
	modrinth {
		token = System.getenv("MODRINTH_TOKEN")
		projectId = 'emi'
		versionNumber = project.version
		versionName = project.version
		versionType = 'release'
		uploadFile = shadowJar
		gameVersions = [rootProject.minecraft_version]
		loaders = ['neoforge']
		detectLoaders = false
		changelog = file('../CHANGELOG.md').text
	}
}

if (System.getenv("CURSEFORGE_TOKEN")) {
	curseforge {
		apiKey = System.getenv("CURSEFORGE_TOKEN")
		project {
			id = '580555'
			releaseType = 'release'
			changelogType = 'markdown'
			changelog = file('../CHANGELOG.md')

			addGameVersion rootProject.minecraft_version
			addGameVersion 'NeoForge'

			mainArtifact(shadowJar.get().archiveFile) {
				displayName = 'emi-' + project.version
			}
		}
		options {
			javaIntegration = false
			forgeGradleIntegration = false
			javaVersionAutoDetect = false
		}
	}
}
